postgresql:
  enabled: true
  auth:
    existingSecret: authentik-creds

redis:
  enabled: true

server:
  env:
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-creds
          key: password
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-creds
          key: secret_key

worker:
  env:
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-creds
          key: password
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-creds
          key: secret_key

  # email:
  #   host: "smtp.gmail.com"
  #   port: 587
  #   username: ""
  #   password: ""
  #   use_tls: true
  #   from: ""
