tz Asia/Kuala_Lumpur
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %^ %^ [%d:%t %^] "%r" %s %b "%R" "%u" %^ "%^" "%^" %^
log-file /srv/traefik-logs/access.log
output /srv/report/report.html
real-time-html true
ws-url wss://goaccess.ora.shafiqtechub.com:443/ws
port 7890