services:
  grafana:
    image: docker.io/grafana/grafana-oss:12.1.1
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.service=grafana
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=cloudflare
    networks:
      - traefik_default
    restart: unless-stopped

networks:
  traefik_default:
    external: true

volumes:
  grafana_data: