image:
  repository: traefik
  tag: v3.5.3
  pullPolicy: IfNotPresent
service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: "192.xxx.xx.xxx"
  ports:
    web:
      port: 80
    websecure:
      port: 443
ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    expose:
      default: true
ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure
    matchRule: Host(`traefik.xxx.com`)
    tls:
      secretName: traefik-certificate-secret
logs:
  general:
    level: ERROR
  access:
    enabled: false