global:
  checkNewVersion: false
  sendAnonymousUsage: false

# metrics:
#   prometheus:
#     addEntryPointsLabels: true
#     addServicesLabels: true

log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
accessLog:
  filePath: "/var/log/traefik/access.log"
  fields:
    headers:
      defaultMode: keep

api:
  dashboard: true
  insecure: true

experimental:
  plugins:
    cloudflarewarp:
      moduleName: "github.com/BetterCorp/cloudflarewarp"
      version: "v1.3.3"

entryPoints:
  web:
    address: :80
    # http:
    #   middlewares:
    #     - crowdsec-bouncer@file
    #     - hsts-headers@file
      # redirections:
      #    entryPoint:
      #      to: websecure
      #      scheme: https
    forwardedHeaders:
      trustedIPs: &trustedIps
        - 127.0.0.1/32
        - 172.18.0.0/16       # Your internal Public Traefik docker network
        - 172.19.0.0/16       # Your internal LAN Traefik docker network
        - 192.168.1.1/32 # Gateway IP
        - 192.168.1.2/32 # Traefik DMZ IP
  websecure:
    address: :443
    http:
      # middlewares:
      #   - crowdsec-bouncer@file
      #   - hsts-headers@file
    forwardedHeaders:
      trustedIPs: *trustedIps       

certificatesResolvers:
  cloudflare:
    acme:
      email: xxx@gmail.com
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# --> (Optional) Disable TLS Cert verification check
serversTransport:
  insecureSkipVerify: true
# <--

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
