http:
  middlewares:
    my-cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault: "false"
          trustip:
            - 2400:cb00::/32
  routers:
    jellyfin:
      entryPoints:
        - web
        - websecure
      rule: "Host(`xxx.xxx.com`)"
      service: jellyfin
      tls:
        certResolver: cloudflare
  services:
    jellyfin:
      loadBalancer:
        servers:
        - url: "http://192.168.1.1:8096"