services:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /mnt/192.168.xx.xx/Share/swarm-data/portainer-data:/data
    networks:
      - traefik_traefik_proxy
      - portainer_internal
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true

        # Traefik HTTPS router
        - traefik.http.routers.portainer.rule=Host(`portainer.xxx.com`)
        - traefik.http.routers.portainer.entrypoints=websecure
        - traefik.http.routers.portainer.tls=true
        - traefik.http.routers.portainer.tls.certresolver=le

        # Portainer service
        - traefik.http.services.portainer.loadbalancer.server.port=9000

  agent:
    image: portainer/agent:latest
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_internal
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

networks:
  traefik_traefik_proxy:
    external: true

  portainer_internal:
    driver: overlay
    attachable: true