roles: app
proxyAddr: teleport.xxxxxx.com:443
authToken: null
joinTokenSecret:
  name: teleport-auth-token
  key: auth-token 

tls:
  secretName: teleport-certificate-secret

resources:
  requests:
    cpu: 100m
    memory: 150Mi
  limits:
    cpu: 2000m
    memory: 2048Mi

# Define your apps here
apps:
  - name: sth01
    description: "STH-01 Dashboard"
    uri: "http://192.168.1.1:81"   # STH-01 Server
    public_addr: "sth01.teleport.xxxxx.com"
    labels:
      environment: dashboard
    rewrite:
      headers:
        - "Host: sth01.teleport.xxxxx.com"
        - "Origin: https://sth01.teleport.xxxxx.com"

  - name: "longhorn"
    description: "Longhorn Dashboard"
    uri: "http://longhorn-frontend.longhorn-system.svc.cluster.local:80"
    public_addr: "longhorn.teleport.xxxxx.com"
    insecure_skip_verify: true
    labels:
      environment: server
    rewrite:
      headers:
        - "Host: longhorn.teleport.xxxxx.com"
        - "Origin: https://longhorn.teleport.xxxxx.com"

  
