version: '3'
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=Etc/UTC
    ports:
      - "8096:8096"
    volumes:
      - /mnt/media:/mnt/media
    restart: unless-stopped
