services:
  app:
    container_name: portainer
    image: docker.io/portainer/portainer-ce:2.29.2-alpine
    ports:
      - 8000:8000
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - traefik.enable=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.rule=Host(`portainer.example.com`)
      - traefik.http.routers.portainer.middlewares=authentik-middleware@file
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=cloudflare
    restart: unless-stopped
    networks:
      - traefik_default

volumes:
  portainer-data:
    driver: local

networks:
  traefik_default:
    external: true
