services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    volumes:
      - ./beszel_data:/beszel_data
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`beszel.local-lab.shafiqtechub.com`)
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.routers.beszel.tls.certresolver=cloudflare
      - traefik.http.routers.beszel.tls=true
      - traefik.http.services.beszel.loadbalancer.server.port=8090
      - traefik.http.routers.beszel.service=beszel  
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true