mqtt:
  enabled: False
environment_vars:
  FRIGATE_RTSP_PASSWORD: $FRIGATE_RTSP_PASSWORD
birdseye:
  enabled: True
  mode: continuous
cameras:
  meowroom:
    ffmpeg:
      inputs:
        - path: rtsp://shafiq:{FRIGATE_RTSP_PASSWORD}@192.168.111.222:554/stream1
          roles:
            - detect
            - record
    onvif:
      host: 192.168.111.222
      port: 2020
      user: shafiq
      password: "{FRIGATE_RTSP_PASSWORD}"
    detect:
      width: 1280
      height: 720
      fps: 30
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: True
      retain:
        days: 1
    birdseye:
      mode: continuous
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://shafiq:{FRIGATE_RTSP_PASSWORD}@192.168.111.222:554/stream1
          roles:
            - detect
    onvif:
      host: 192.168.111.222
      port: 2020
      user: shafiq
      password: "{FRIGATE_RTSP_PASSWORD}"
    detect:
      width: 1920
      height: 1080
      fps: 30
    objects:
      track:
        - person
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: True
      retain:
        days: 1
    birdseye:
      mode: continuous
