mqtt:
  enabled: False
environment_vars:
  FRIGATE_RTSP_PASSWORD: $FRIGATE_RTSP_PASSWORD

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

birdseye:
  enabled: True
  mode: continuous
cameras:
  meowroom:
    ffmpeg:
      inputs:
        - path: rtsp://shafiq:{FRIGATE_RTSP_PASSWORD}@192.168.111.222:554/stream1
          roles:
            - detect
            - record
    onvif:
      host: 192.168.111.222
      port: 2020
      user: shafiq
      password: "{FRIGATE_RTSP_PASSWORD}"
    detect:
      width: 1280
      height: 720
      fps: 30
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: True
      retain:
        days: 1
    birdseye:
      mode: continuous
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://shafiq:{FRIGATE_RTSP_PASSWORD}@192.168.111.222:554/stream1
          roles:
            - detect
    onvif:
      host: 192.168.111.222
      port: 2020
      user: shafiq
      password: "{FRIGATE_RTSP_PASSWORD}"
    detect:
      width: 1920
      height: 1080
      fps: 30
    objects:
      track:
        - person
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: True
      retain:
        days: 1
    birdseye:
      mode: continuous

