services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
    # depends_on:  #uncomment if running traefik in the same compose file
    #   - 'traefik'
    volumes:
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - crowdsec-db:/var/lib/crowdsec/data/
      - traefik_traefik-logs:/var/log/traefik/:ro
    networks:
      - traefik_default
    restart: unless-stopped

  bouncer-traefik:
    image: docker.io/fbonalair/traefik-crowdsec-bouncer:latest
    container_name: bouncer-traefik
    environment:
      CROWDSEC_BOUNCER_API_KEY: $CROWDSEC_BOUNCER_API_KEY
      CROWDSEC_AGENT_HOST: crowdsec:8080
    networks:
      - traefik_default
    depends_on:
      - crowdsec
    restart: unless-stopped


  crowdsec-dashboard:
    # Default login:
    #   crowdsec@crowdsec.net
    #   !!Cr0wdS3c_M3t4b4s3??
    build: ./dashboard
    container_name: crowdsec-dashboard
    restart: unless-stopped
    environment:
        MB_DB_FILE: /data/metabase.db
        MGID: "${GID-1000}" # Needs access to crowdsec.db file
    depends_on:
      - crowdsec
    volumes:
        #- metabase-db:/data/
      - crowdsec-db:/metabase-data/
    labels:
      - traefik.enable=true
      - traefik.http.routers.crowdsec-dashboard.entrypoints=websecure
      - traefik.http.routers.crowdsec-dashboard.tls.certresolver=cloudflare
      - traefik.http.routers.crowdsec-dashboard.tls=true
      - traefik.http.services.crowdsec-dashboard.loadbalancer.server.port=3000
      - traefik.http.routers.crowdsec-dashboard.service=crowdsec-dashboard
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
volumes:
  crowdsec-db:
  traefik_traefik-logs: # this will be the name of the volume from trarfic logs
    external: true # remove if traefik is running on same stack

# To add bouncer to traefik
# docker exec crowdsec cscli bouncers add bouncer-traefik

# To test if crowdsec is working, you can run the following command to see the decisions made by crowdsec
# docker exec crowdsec cscli metrics
# docker exec crowdsec cscli decisions list
# docker exec crowdsec cscli decisions add --ip 192.168.xxx.xxx
# docker exec crowdsec cscli decisions delete --ip 192.168.xxx.xxx